//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.commonsware.empublite;

import android.app.DownloadManager;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.support.v4.app.Fragment;
import org.apache.http.conn.ClientConnectionManager;
import org.apache.http.conn.ssl.SSLSocketFactory;
import org.apache.http.impl.client.DefaultHttpClient;

public final class DownloadCheckService_
    extends DownloadCheckService
{


    public static DownloadCheckService_.IntentBuilder_ intent(Context context) {
        return new DownloadCheckService_.IntentBuilder_(context);
    }

    public static DownloadCheckService_.IntentBuilder_ intent(Fragment supportFragment) {
        return new DownloadCheckService_.IntentBuilder_(supportFragment);
    }

    private void init_() {
        prefs = new DownloadPrefs_(this);
        mgr = ((DownloadManager) this.getSystemService(Context.DOWNLOAD_SERVICE));
        httpsClient = new DefaultHttpClient() {


            @Override
            protected ClientConnectionManager createClientConnectionManager() {
                try {
                    ClientConnectionManager ccm = super.createClientConnectionManager();
                    ((SSLSocketFactory) ccm.getSchemeRegistry().getScheme("https").getSocketFactory()).setHostnameVerifier(SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);
                    return ccm;
                } catch (Exception e) {
                    e.printStackTrace();
                    return super.createClientConnectionManager();
                }
            }

        }
        ;
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, DownloadCheckService_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, DownloadCheckService_.class);
        }

        public Intent get() {
            return intent_;
        }

        public DownloadCheckService_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public ComponentName start() {
            return context_.startService(intent_);
        }

        public boolean stop() {
            return context_.stopService(intent_);
        }

    }

}
