//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.commonsware.empublite;

import android.app.NotificationManager;
import android.content.Context;
import android.content.Intent;

public final class InstallReceiver_
    extends InstallReceiver
{

    private Context context_;

    private void init_() {
        mgr = ((NotificationManager) context_.getSystemService(Context.NOTIFICATION_SERVICE));
    }

    @Override
    public void onReceive(Context context, Intent intent) {
        context_ = context;
        init_();
        super.onReceive(context, intent);
    }

}
